Like button functionality
ubclaunchpad/umami pull request #28
Opened 2021-11-20 19:49 UTC by NicholasKao1029

Initial PR for like button functionality

2021-11-21 22:37 UTC, Harin329 requested changes

2021-11-21 22:37 UTC, Harin329 commented on tmp.txt
> +POST /user_activity/
was this file just for your own reference? maybe we can remove this from the commit

2021-11-21 22:37 UTC, Harin329 commented on frontend/src/screens/tab1/recipe.js
> +            <TouchableOpacity activeOpacity={0.5} onPress={this.Func}>
So this on press is where your logic should trigger the endpoint. A dispatch should be called with your action (POST_RECIPE_LIKE) and the param. So something along the lines of onPress={() => {dispatch({type: GET_RECIPE, recipe_id: recipe.recipe_id})}}, but naming the `recipe_id` param part accordingly to the saga function (recipe_like_id).

2021-11-21 22:37 UTC, Harin329 commented on frontend/src/screens/tab1/recipe.js
> +            <TouchableOpacity activeOpacity={0.5} onPress={this.Func}>
a suggestion would be to just make a mapping like { recipe_like_id: 'id', user_id: 'id'} and attach that object as a part of the dispatch so u can access multiple params

2021-11-25 02:09 UTC, NicholasKao1029 commented on frontend/src/screens/tab1/recipe.js
> +            <TouchableOpacity activeOpacity={0.5} onPress={this.Func}>
Currently doing

```
                dispatch({
                  type: POST_RECIPE_LIKE,
                  user_id: auth().currentUser.uid,
                  recipe_like_id: recipe.recipe_id,
                });
```

Does it not work with more keys than one?

2021-11-27 19:52 UTC, Harin329 approved these changes

2021-11-27 19:52 UTC, merged